[global]
log_level = 'info'
[mode]
[mode.clients]
enabled = true
refresh = true
misbehaviour = false
[mode.connections]
enabled = false
[mode.channels]
enabled = false
[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = false
[rest]
enabled = true
host = '127.0.0.1'
port = 3000
[telemetry]
enabled = false
host = '127.0.0.1'
port = 3001
[[chains]]
id = 'evmos_9001-2'
rpc_addr = 'http://127.0.0.1:26657'
grpc_addr = 'http://127.0.0.1:26652'
websocket_addr = 'ws://127.0.0.1:26657/websocket'
rpc_timeout = '10s'
account_prefix = 'evmos'
key_name = 'evmos_relayer'
address_type = { derivation = 'ethermint', proto_type = { pk_type = '/ethermint.crypto.v1.ethsecp256k1.PubKey' } }
store_prefix = 'ibc'
default_gas = 5000000
max_gas = 5500000
gas_price = { price = 20000000000, denom = 'aevmos' }
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '30s'
trusting_period = '10days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Relayed by Architect Nodes! '
[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', 'channel-3'], #Cosmos
  ['transfer', 'channel-0'], # osmosis-1
  ['transfer', 'channel-25'], #stride-1
 ]
[[chains]]
id = 'cosmoshub-4'
rpc_addr = 'http://127.0.0.1:26727'
grpc_addr = 'http://127.0.0.1:26722'
websocket_addr = 'ws://127.0.0.1:26727/websocket'
rpc_timeout = '10s'
account_prefix = 'cosmos'
key_name = 'cosmos_relayer'
store_prefix = 'ibc'
default_gas = 650000
max_gas = 700000
gas_price = { price = 0.002, denom = 'uatom' }
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 180000
clock_drift = '5s'
max_block_time = '30s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }
memo_prefix = 'Relayed by Architect Nodes! '
[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', 'channel-292'], #EVMOS
  ['transfer', 'channel-229'], #bitsong-2b
  ['transfer', 'channel-391'], #stride-1
  ['transfer', 'channel-141'], #osmosis-1
 ]
[[chains]]
id = 'osmosis-1'
rpc_addr = 'http://127.0.0.1:26737'
grpc_addr = 'http://127.0.0.1:26732'
websocket_addr = 'ws://127.0.0.1:26737/websocket'
rpc_timeout = '10s'
account_prefix = 'osmo'
key_name = 'osmosis_relayer'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 500000
max_gas = 1000000
gas_price = { price = 0.001, denom = 'uosmo' }
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '30s'
trusting_period = '10days'
memo_prefix = 'Relayed by Architect Nodes! '
trust_threshold = { numerator = '1', denominator = '3' }
[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', 'channel-73'],  # bitsong-2b 
  ['transfer', 'channel-204'], # EVMOS
  ['transfer', 'channel-229'], # fetchhub-4
  ['transfer', 'channel-0'],   # cosmoshub-4
  ['transfer', 'channel-326'], # stride-1
  ['transfer', 'channel-4'],   # core-1
]
[[chains]]
id = 'bitsong-2b'
rpc_addr = 'http://127.0.0.1:26627'
grpc_addr = 'http://127.0.0.1:26622'
websocket_addr = 'ws://127.0.0.1:26627/websocket'
rpc_timeout = '10s'
account_prefix = 'bitsong'
key_name = 'bitsong_relayer'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 800000
max_gas = 1000000
gas_price = { price = 0.026, denom = 'ubtsg' }
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '30s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Relayed by Architect Nodes! '
[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', 'channel-0'], #osmosis-1
  ['transfer', 'channel-1'], #cosmoshub-4
 ]
[[chains]]
id = 'fetchhub-4'
rpc_addr = 'http://127.0.0.1:26617'
grpc_addr = 'http://127.0.0.1:26612'
websocket_addr = 'ws://127.0.0.1:26617/websocket'
rpc_timeout = '20s'
account_prefix = 'fetch'
key_name = 'fetch_relayer'
store_prefix = 'ibc'
default_gas = 1500000
max_gas = 2000000
gas_price = { price = 0.25, denom = 'afet' }
gas_multiplier = 1.1
max_msg_num = 15
max_tx_size = 180000
clock_drift = '5s'
max_block_time = '30s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }
memo_prefix = 'Relayed by Architect Nodes! '
[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', 'channel-10'], #osmosis-1
 ]
[[chains]]
id = 'stride-1'
rpc_addr = 'http://127.0.0.1:26637'
grpc_addr = 'http://127.0.0.1.246:26632'
websocket_addr = 'ws://127.0.0.1:26637/websocket'
rpc_timeout = '10s'
account_prefix = 'stride'
key_name = 'stride_relayer'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 900000
max_gas = 1000000
gas_price = { price = 0.00005, denom = 'ustrd' }
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '30s'
trusting_period = '10days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'Relayed by Architect Nodes! '
 [chains.packet_filter]
 policy = 'allow'
 list = [
    ['transfer', 'channel-0'], # cosmoshub-4
    ['transfer', 'channel-9'], # evmos_9001-2
    ['transfer', 'channel-5'], # osmosis-1
 ]
[[chains]]
id = 'core-1'
rpc_addr = 'http://127.0.0.1:26697'
grpc_addr = 'http://127.0.0.1:26692'
websocket_addr = 'ws://127.0.0.1:26697/websocket'
rpc_timeout = '10s'
account_prefix = 'persistence'
key_name = 'persistence_relayer'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 400000
max_gas = 640000
gas_price = { price = 0.003, denom = 'uxprt' }
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '30s'
trusting_period = '14days'
memo_prefix = 'Relayed by Architect Nodes! '
trust_threshold = { numerator = '1', denominator = '3' }
[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', 'channel-6'], # osmosis-1
]
